language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - "nightly"

install:
  - pip install pytest pytest-cov
  - python setup.py install

script:
  - py.test --cov=historydict --cov-report term-missing

after_success:
  - coveralls
