language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - "3.5.0b4"
  
install:
  - python setup.py install
  - pip install six pytest pytest-cov

script:
  - py.test --cov=historydict --cov-report term-missing

after_success:
  coveralls
