language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "nightly"

install:
  - pip install pytest pytest-cov
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]] || [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then
        pip install weakrefmethod;
    fi;
  - python setup.py install

script:
  - py.test --cov=historydict --cov-report term-missing

after_success:
  - coveralls
