language: python
env:
  global:
    secure: "hu6ot+paAEZ2yV/f0wyPpUZD16FWeYEAmUi2yYmJL+KWewK/6+Nwf6UMD7vcX3v1tgFOmzjL1LZSkRVFiFF35+bt30uy++5s9xKVzeNLWi7amIj9Q0x2E1iVQmBdCj0qCMpgonGe1VJ/j2ORSfLDzsDjnNDP4VL/Cli8dQM6Kxph6pkosoCvTGuCpN9AO4a3n023XoFgXyLo1JvCoWkV3CtdUko5GQ55es82MYCQ1JD7qNzRkFuBpEa6QvbQ0SjGvoe36SrkzXh/9kuvjf5bv3zGmwFsG2kFPaDAZAo8zthdBtk/qlHwJ+p145WlViYvv1AGsbpL90Xd4vwyUNLP+Us93L6e/mQFKA3PoRZFX6RHUZclZYypURcy3uB72WkQxWHK7gMMARsj9M6VWRhI6Cn4E+4owmabGArfjrChPUgmVtYZc+WNtgOd5Z9BSFpv+rfLcrHMMXGF/h8180ftt/uj7x4BGCLlNXXXXDXKK3pPKE76pdNMdBhd6Ws/O2yCmlgbvbzESs7fkp4gTJFZ1BNby4wE/hjOqsksjdKYU4i0ze8Y1fBSEdmF90dGZMhyYSg3dsESlwNbc3/QI6FOUlmv26qDgmdWNx6F49gqmIUlR+NMP3SNM4yngwO2eBbTIWJWdfv8ZR9Jw6vnaF8pzUvOZCCFqZvnmc46xpXnPnM="
git:
  # hack around git fetch --unshallow failing if the number of commits are
  # less than 50
  depth: 9999999

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "nightly"

before_install:
  - git clone https://gist.github.com/613e015ad558b9149d33.git ~/scripts
  - chmod +x ~/scripts/*.sh
  - . ~/scripts/install-miniconda.sh
  # - git fetch --unshallow
  # - source ~/.bashrc
install:
  - python setup.py install
  - pip install six pytest pytest-cov

script:
  - py.test --cov=historydict --cov-report term-missing
  - . ~/scripts/conda-build.sh
  # - if [[ ( "$TRAVIS_PYTHON_VERSION" != 'nightly' ) ]] ; then
  #     $CONDA_BUILD_COMMAND;
  #   fi;

after_success:
  - coveralls
  - . ~/scripts/anaconda-upload.sh
  # - if [[ ( "$TRAVIS_PYTHON_VERSION" != 'nightly' ) && ( "$TRAVIS_PULL_REQUEST" == 'false' ) && ( "$TRAVIS_BRANCH" == 'auto-build-on-travis' ) ]] ; then
  #     anaconda -t ${BINSTAR_TOKEN} upload $($CONDA_BUILD_COMMAND --output) -u lightsource2 -c development --force;
  #   fi;


